apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: nginx1
  name: nginx1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx1
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disk
                operator: In
                values:
                - fast
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: disk
                operator: In
                values:
                - fast
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
